services:
  golang-postgres:
    image: postgres:13.3
    container_name: go-postgres
    ports:
      - 6500:5432
    env_file:
      - ./app.env
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:


